version: 2.1

orbs: 
  allure: ayte/allure@0.1.3

jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - allure/install

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: clean Allure report generation path
          command: rm -rf reports/allure-report
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run: mkdir test-reports
      - run: mkdir test-reports/images
      - run: mkdir allure-results

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            pytest test_nippou.py
      - store_artifacts:
          path: test-reports/
          destination: test-reports

      - store_test_results:
          path: test-results

      - allure/report

workflows:
 version: 2
 normal_workflow:
   jobs:
     - build
 schedule_workflow:
   triggers:
     - schedule:
         cron: "39 5 * * *" # UTCで記述。-9
         filters:
           branches:
             only:
               - main
   jobs:
     - build