version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8.13-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: RegisterToDB
          command: |
            . venv/bin/activate
            pytest test_nippou.py

workflows:
 version: 2
 normal_workflow:
   jobs:
     - build
 schedule_workflow:
   triggers:
     - schedule:
         cron: "39 5 * * *" # UTCで記述。-9
         filters:
           branches:
             only:
               - main
   jobs:
     - build