version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: RegisterToDB
          command: |
            . venv/bin/activate
            sleep $(($RANDOM % 900))
            pytest test_WorkStartDB.py

workflows:
 version: 2
#  normal_workflow:
#    jobs:
#      - build
 schedule_workflow:
   triggers:
     - schedule:
         cron: "35 23 * * 1,2,3,4,5" # UTCで記述。指定時刻から-9時間。8時35分〜50分までの間に実行
         filters:
           branches:
             only:
               - main
   jobs:
     - build